# Generated by Django 5.0 on 2023-12-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0002_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='refresh_token',
        ),
    ]
