# Generated by Django 5.0 on 2023-12-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0003_remove_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
    ]
