# Generated by Django 5.0 on 2023-12-27 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertrackplaylist',
            unique_together={('username', 'playlist_name', 'track_id')},
        ),
    ]
