# Generated by Django 5.0 on 2023-12-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0007_alter_usertrackplaylist_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTrackPlaylist',
        ),
    ]
