# Generated by Django 5.0 on 2024-01-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify_api', '0008_delete_usertrackplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFeatures',
            fields=[
                ('track_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('artist', models.CharField(default=None, max_length=255, null=True)),
                ('features', models.JSONField(null=True)),
            ],
        ),
    ]
