# Generated by Django 5.0 on 2024-01-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfeatures',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trackfeatures',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
