# Generated by Django 5.0 on 2024-01-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0010_alter_trackfeatures_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfeatures',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
