# Generated by Django 5.0 on 2024-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0012_rename_image_url_trackfeatures_track_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfeatures',
            name='artist_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
