# Generated by Django 5.0 on 2024-02-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0012_rename_image_url_trackfeatures_track_img'),
        ('user_tracks', '0004_rename_track_id_id_userinterestedtracks_track_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikedtracks',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_liked_tracks', to='spotify_api.trackfeatures', verbose_name='Track ID'),
        ),
    ]
