# Generated by Django 5.0 on 2024-02-24 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0012_rename_image_url_trackfeatures_track_img'),
        ('user_tracks', '0008_alter_usertrackplaylist_track_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrackplaylist',
            old_name='track_id',
            new_name='track_id_id',
        ),
        migrations.AlterUniqueTogether(
            name='usertrackplaylist',
            unique_together={('username', 'playlist_name', 'track_id_id')},
        ),
    ]
